# Generated by Django 4.1.6 on 2023-02-16 14:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('designation', models.CharField(max_length=250, verbose_name='Должность')),
                ('photo', models.ImageField(null=True, upload_to='photo/account/%Y/%m/%d')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text_feedback', models.CharField(max_length=500, verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='sometable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tour_name', models.CharField(max_length=255, verbose_name='Название тура')),
                ('price', models.IntegerField(verbose_name='Стоимость тура')),
                ('duration_tour', models.IntegerField(default=1, verbose_name='Длительность тура')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('country', models.CharField(choices=[('USA', 'USA'), ('IND', 'Indonesia'), ('IN', 'India'), ('RF', 'Russia'), ('GB', 'Great Britain'), ('KZ', 'Kazakhstan'), ('KG', 'Kyrgyzstan'), ('EG', 'Egypt'), ('KT', 'Katar'), ('TR', 'Turkey'), ('GR', 'Georgia'), ('SA', 'Saudi Arabia'), ('BZ', 'Brazil')], max_length=100, verbose_name='Страна')),
                ('hotel', models.CharField(max_length=255, verbose_name='Название отеля')),
                ('numb_seats_room', models.IntegerField(verbose_name='Количество мест в номере')),
                ('numb_bath_room', models.IntegerField(verbose_name='Количество ванн в номере')),
                ('nearby', multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Mountains'), ('B', 'Beach'), ('S', 'Skiing'), ('SF', 'Safari')], max_length=255, verbose_name='Поблизости есть: ')),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='photos/tour/%Y/%m/%d/', verbose_name='Главное фото')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание тура')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавление тура')),
                ('start_date', models.DateField(blank=True, verbose_name='Дата начала тура')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Tour_Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.FileField(upload_to='photos/tour/tour_photos/%Y/%m/%d/')),
                ('tour_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.tours')),
            ],
            options={
                'verbose_name': 'Tour photo',
                'verbose_name_plural': 'Tour photos',
            },
        ),
    ]
