# Generated by Django 4.1.6 on 2023-04-09 09:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('designation', models.CharField(max_length=250, verbose_name='Должность')),
                ('photo', models.ImageField(null=True, upload_to='photo/account/%Y/%m/%d')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text_feedback', models.CharField(max_length=500, verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
