# Generated by Django 4.1.6 on 2023-02-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sometable',
        ),
    ]
