# Generated by Django 4.1.6 on 2023-04-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_delete_sometable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tour_Photo',
        ),
        migrations.DeleteModel(
            name='Tours',
        ),
    ]
