# Generated by Django 4.1.6 on 2023-03-18 11:20

import ckeditor.fields
from django.db import migrations, models
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('text', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/cars/%Y/%m/%d/')),
                ('categories', multiselectfield.db.fields.MultiSelectField(choices=[('Travel', 'Travel'), ('Tour', 'Tour'), ('Destination', 'Destination'), ('Drinks', 'Drinks'), ('Food', 'Food')], max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
