# Generated by Django 4.1.6 on 2023-03-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/blogs/%Y/%m/%d/'),
        ),
    ]
