# Generated by Django 4.1.6 on 2023-03-20 12:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Travel', 'Travel'), ('Tour', 'Tour'), ('Destination', 'Destination'), ('Drinks', 'Drinks'), ('Food', 'Food')], max_length=40),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(related_name='tags', related_query_name='tags+', to='blog.tag'),
        ),
    ]
