# Generated by Django 4.1.6 on 2023-03-20 13:14

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_alter_blog_categories_blog_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', multiselectfield.db.fields.MultiSelectField(choices=[('Travel', 'Travel'), ('Tour', 'Tour'), ('Destination', 'Destination'), ('Drinks', 'Drinks'), ('Food', 'Food')], max_length=40)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='blog',
            name='categories',
        ),
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(related_name='categories', related_query_name='categories+', to='blog.categories'),
        ),
    ]
