# Generated by Django 4.1.6 on 2023-03-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_categories_remove_blog_categories_blog_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(to='blog.categories'),
        ),
    ]
