# Generated by Django 4.1.6 on 2023-04-03 13:46

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_title_categories_name_alter_blog_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='blog.categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=multiselectfield.db.fields.MultiSelectField(choices=[['Travel', 'Travel'], ['Tour', 'Tour'], ['Destination', 'Destination'], ['Drinks', 'Drinks'], ['Food', 'Food']], max_length=40),
        ),
    ]
