# Generated by Django 4.1.6 on 2023-04-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_delete_categories_alter_blog_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_date']},
        ),
    ]
