# Generated by Django 4.1.6 on 2023-04-05 13:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('short_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Nearby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Nearby',
                'verbose_name_plural': 'Nearbies',
            },
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tour_name', models.CharField(max_length=255, verbose_name='Название тура')),
                ('price', models.IntegerField(verbose_name='Стоимость тура')),
                ('duration_tour', models.IntegerField(default=1, verbose_name='Длительность тура')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('hotel', models.CharField(max_length=255, verbose_name='Название отеля')),
                ('numb_seats_room', models.IntegerField(verbose_name='Количество мест в номере')),
                ('numb_bath_room', models.IntegerField(verbose_name='Количество ванн в номере')),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='photos/tour/%Y/%m/%d/', verbose_name='Главное фото')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание тура')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавление тура')),
                ('start_date', models.DateField(blank=True, verbose_name='Дата начала тура')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.country', verbose_name='Страна')),
                ('nearby', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.nearby', verbose_name='Поблизости есть: ')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Tour_Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.FileField(upload_to='photos/tour/tour_photos/%Y/%m/%d/')),
                ('tour_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.tours')),
            ],
            options={
                'verbose_name': 'Tour photo',
                'verbose_name_plural': 'Tour photos',
            },
        ),
    ]
