# Generated by Django 4.1.6 on 2023-04-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour_photo',
            name='tour_photo',
        ),
        migrations.RemoveField(
            model_name='tours',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tours',
            name='nearby',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Tour_Photo',
        ),
        migrations.DeleteModel(
            name='Tours',
        ),
    ]
