# Generated by Django 4.1.6 on 2023-04-06 14:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_remove_tour_photo_tour_photo_remove_tours_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('slug', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('short_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/countries/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tour_name', models.CharField(max_length=255, verbose_name='Название тура')),
                ('price', models.IntegerField(verbose_name='Стоимость тура')),
                ('duration_tour', models.IntegerField(default=1, verbose_name='Длительность тура')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('hotel', models.CharField(max_length=255, verbose_name='Название отеля')),
                ('numb_seats_room', models.IntegerField(verbose_name='Количество мест в номере')),
                ('numb_bath_room', models.IntegerField(verbose_name='Количество ванн в номере')),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='photos/tour/%Y/%m/%d/', verbose_name='Главное фото')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание тура')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавление тура')),
                ('start_date', models.DateField(blank=True, verbose_name='Дата начала тура')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_tours', to='tours.country', verbose_name='Страна')),
                ('nearby', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.nearby', verbose_name='Поблизости есть: ')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'ordering': ['created_date'],
            },
        ),
    ]
