# Generated by Django 4.1.6 on 2023-04-07 08:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_country_tours'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='about_country',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание страны'),
        ),
    ]
